config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  post "/login", to: "sessions#login"
  # 打鍵して不要であれば削除
  # post "/request_change_login", to: "sessions#request_change_login"

  get "/forgot_password", to: "sessions#forgot_password"
  post "/send_reset_password_email", to: "sessions#send_reset_password_email"
  get "/:token/new_password", to: "sessions#new_password", as: "new_password"
  post "/reset_password", to: "sessions#reset_password"

  # キャンセル依頼トップ
  get "/forms/request_change_top", to: "forms#request_change_top"
  # キャンセル依頼ログイン
  post "/forms/request_change_login", to: "forms#request_change_login"
  # キャンセル依頼コンタクト送信フォーム
  get "/forms/request_change_contact", to: "forms#request_change_contact"
  # キャンセル依頼POST
  post "/forms/creation_request_change", to: "forms#creation_request_change"


  get "/forms/top", to: "forms#top"
  get "/forms/select_working_location", to: "forms#select_working_location"
  post "/forms/register_working_location", to: "forms#register_working_location"
  post "/forms/destroy_working_location", to: "forms#destroy_working_location"
  get "/forms/select_menu", to: "forms#select_menu"
  get "/forms/select_day", to: "forms#select_day"
  get "/forms/select_time", to: "forms#select_time"
  get "/forms/input_info", to: "forms#input_info"
  get "/forms/confirm", to: "forms#confirm"
  get "/forms/success", to: "forms#success"
  get "/forms/help", to: "forms#help"
  post "/forms/apply_reservation", to: "forms#apply_reservation"
  get "/", to: "reservations#index"
  devise_for :staffs, controllers: {
    sessions: "staffs/sessions",
    registrations: "staffs/registrations",
    passwords: "staffs/passwords"
  }
  devise_scope :staff do
    get "/staffs/sign_out" => "devise/sessions#destroy"
  end

  resources :staffs do
    post "create_account", on: :collection
  end
  resources :travel_fees
  resources :car_wash_menus do
    get "copy", on: :member
  end
  resources :car_wash_options do
    get "copy", on: :member
    get :search, on: :collection
  end
  resources :reservations do
    post "/send_email", to: "reservations#send_email", on: :member
    get "/request_read", to: "reservations#request_read", on: :member
  end
  resources :customers
  resources :working_locations
  resources :staff_shifts do
    get "/", to: "staff_shifts#calendar", on: :collection
    get "/staff_calendar", to: "staff_shifts#staff_calendar", on: :collection
    get "/bulk_input", to: "staff_shifts#bulk_input", on: :collection
    get "/bulk_chenge_input", to: "staff_shifts#bulk_chenge_input", on: :collection
    post "/bulk_register", to: "staff_shifts#bulk_register", on: :collection
  end

  namespace :api do
    get "staff_shift_model_list", to: "staff_shifts#staff_shift_model_list"
    get "car_size_list", to: "select_menus#car_size_list"
    get "car_maker_list", to: "select_menus#car_maker_list"
    get "car_model_list", to: "select_menus#car_model_list"
    get "menu_and_option_list", to: "select_menus#menu_and_option_list"
    get "working_location", to: "select_menus#working_location"
    get "assignable_staff_list", to: "select_menus#assignable_staff_list"
  end
end

app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  include Discard::Model
  include Request::RequestGeo

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations
  has_many :staff_shifts

  validates :family_name, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :role, presence: true

  validates :gender, presence: true, on: :update
  validates :phone, presence: true, if: :phone_number_check?, on: :update
  validates :postal_code, presence: true, if: :postal_code_check?, on: :update
  validates_uniqueness_of :phone, conditions: -> { where(discarded_at: nil) }, on: :update

  enum role: { admin: "admin", staff: "staff" }
  enum gender: { male: "male", female: "female", not_set: "not_set" }

  scope :role_staff, -> { where(role: "staff") }
  scope :role_admin, -> { where(role: "admin") }

  def self.active_staff_on_date(date)
    staffs = Staff.role_staff.filter_map do |staff|
      staff if staff.staff_shifts.where(start_at: date.all_day)
    end
    staff_ids = staffs.map(&:id)
    Staff.where(id: staff_ids)
  end

  def available(start_at, required_time, w_postal_code, res = nil)
    # 予約のupdateで使う場合は現在の予約を第四引数に渡す
    end_at = start_at + required_time
    return nil if role == "admin"
    return nil if staff_shifts.where(start_at: start_at.all_day).where("start_at <= ?", start_at).where("end_at >= ?", start_at + required_time).blank?
    return nil if reservations.where.not(id: res&.id).map { |res| (res.start_at <= start_at && start_at <= res.end_at) || (res.start_at <= end_at && end_at <= res.end_at) }.include?(true)
    self if check_available_outbound(start_at, w_postal_code, res) && check_available_inbound(start_at, required_time, w_postal_code, res)
  end

  def full_name
    "#{family_name} #{name}"
  end

  def full_address
    "#{prefecture} #{address}"
  end

  def check_have_reservation
    errors.add(:base, "予約に紐づいているため、削除できません") if reservations.present?
  end

  private
    def phone_number_check?
      return true if phone.blank?
      return errors.add(:phone, "-(ハイフン)は入れないでください") if phone.match?(/[-]/)
      return errors.add(:phone, "10または11桁にしてください") unless phone.match?(/\A\d{10,11}\z/)
    end

    def postal_code_check?
      return true if postal_code.blank?
      return errors.add(:postal_code, "-(ハイフン)は入れないでください") if postal_code.match?(/[-]/)
      return errors.add(:postal_code, "7桁にしてください") unless postal_code.match?(/\A\d{7}\z/)
    end

    def check_available_outbound(start_at, w_postal_code, res = nil)
      # 事前の予約から間に合うか
      before_reservation = reservations.where.not(id: res&.id).where(end_at: start_at.beginning_of_day..start_at).sort_by { |re| re.end_at }.last
      # initialize
      before_end_at = staff_shifts.find_by(start_at: start_at.all_day).start_at # 事前の予約がなければシフトの開始時間
      outbound_time = 0.minutes # 事前の予約がなければ移動時間なし

      if before_reservation.present?
        before_end_at, before_w_postal_code = [before_reservation.end_at, before_reservation.working_location.postal_code]
        outbound_time = travel_time(before_w_postal_code, w_postal_code).minutes + buffer_time.minutes
      end
      (before_end_at + outbound_time) <= start_at
    end

    def check_available_inbound(start_at, required_time, w_postal_code, res = nil)
      # 事後の予約に間に合うか
      after_reservation = reservations.where.not(id: res&.id).where(start_at: start_at..start_at.end_of_day).sort_by { |re| re.start_at }.first
      # initialize
      after_start_at = staff_shifts.find_by(start_at: start_at.all_day).end_at # 事後の予約がなければシフトの終了時間
      inbound_time = 0.minutes # 事後の予約がなければ移動時間なし

      if after_reservation.present?
        after_start_at, after_w_postal_code = [after_reservation.start_at, after_reservation.working_location.postal_code]
        inbound_time = travel_time(w_postal_code, after_w_postal_code).to_i.minutes + buffer_time.minutes
      end
      current_end_at = start_at + required_time

      (current_end_at + inbound_time) <= after_start_at
    end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staffs::PasswordsController < Devise::PasswordsController
  layout "devise_form"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      redirect_to new_staff_password_path, data: { turbo: false }
    else
      flash[:error] = resource.errors.full_messages.join(",")
      redirect_to new_staff_password_path, data: { turbo: false }
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?
    if resource.errors.empty?
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:notice, flash_message)
        resource.after_database_authentication
        sign_in(resource_name, resource)
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      redirect_to "/", data: { turbo: false }
    else
      flash[:error] = resource.errors.full_messages.join(",")
      redirect_to edit_staff_password_path(reset_password_token: params[:staff][:reset_password_token]), data: { turbo: false }
    end
  end

  # protected

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  layout "devise_form"
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    redirect_to new_staff_path
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the staff wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  layout "devise_form"
end

app/controllers/staffs_controller.rb
# frozen_string_literal: true

class StaffsController < ApplicationController
  before_action :authenticate_staff!
  before_action :authenticate_role_admin!, only: [:new, :create, :edit, :update, :destroy, :create_account]

  def index
    staffs = search_index(params)
    @staffs = staffs.order(created_at: "desc").page(params[:page]).per(30)
  end

  def show
    @staff = Staff.find_by(id: params[:id])
  end

  def new
    @staff = Staff.new
  end

  def create_account
    @staff = Staff.new(staff_params)
    begin
      if @staff.save
        StaffMailer.welcome(@staff).deliver_now
        flash[:notice] = "スタッフを作成しました。"
        redirect_to staffs_path
      else
        render "new"
      end
    rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError, ActiveRecord::RecordInvalid => e
      Rails.logger.error("メール送信に失敗しました。システム担当者にご連絡ください。 #{e.message}")
      redirect_to staffs_path, flash: { error: "メール送信に失敗しました。システム担当者にご連絡ください。 #{e.message}" }
    end
  end

  def edit
    @staff = Staff.find_by(id: params[:id])
  end

  def update
    @staff = Staff.find(params[:id])
    target_params = staff_params[:password].present? ? staff_params : update_without_current_password_params
    if @staff.update(target_params)
      flash[:notice] = "スタッフを更新しました"
      redirect_to staffs_path
    else
      render "edit"
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.check_have_reservation
    if @staff.errors.blank? && @staff.discard
      @staff.staff_shifts&.map(&:discard)
      flash[:notice] = "スタッフを削除しました"
      redirect_to staffs_path
    else
      errors = @staff.errors&.full_messages
      errors.unshift("スタッフを削除できませんでした。")
      flash.now[:errors] = errors

      redirect_to staffs_path
    end
  end

  private
    def search_index(params)
      staffs = Staff.all
      params[:name]&.gsub("　", " ")&.split(" ")&.map do |str|
        staffs = staffs.where("family_name LIKE ?", "%#{str}%").or(staffs.where("name LIKE ?", "%#{str}%"))
      end
      staffs = staffs.where(role: params[:role]) if params[:role].present?
      # 住所あいまい検索
      params[:address]&.gsub(" ", ",")&.gsub("　", ",")&.gsub("、", ",")&.split(",")&.map do |str|
        staffs = staffs.where("prefecture LIKE ?", "%#{str}%").or(staffs.where("address LIKE ?", "%#{str}%"))
      end
      staffs
    end

    def staff_params
      params.require(:staff)
            .permit(
              :family_name, :name, :email, :password, :password_confirmation, :role, :birthday,
              :phone, :gender, :postal_code, :prefecture, :address, :hobby, :memo, :buffer_time
            )
    end

    def update_without_current_password_params
      params.require(:staff)
            .permit(
              :family_name, :name, :email, :role, :birthday,
              :phone, :gender, :postal_code, :prefecture, :address, :hobby, :memo, :buffer_time
            )
    end
end

app/views/staffs/_form.html.slim
script[src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"]
.card.col-sm-12.shadow.p-3.mb-4.bg-body.rounded
  .row.g-1.col-sm-12.col-md-12.col-lg-6
    .col.col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:family_name)}
      = f.text_field :family_name, class: "form-control"
    .col.col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:name)}
      = f.text_field :name, class: "form-control"
  .col-sm-6.pb-3
    label.pb-2 #{Staff.human_attribute_name(:email)}
    = f.email_field :email, autocomplete: "email", class: "form-control"
  - if f.object.new_record?
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:password)}
      = f.password_field :password, autocomplete: "new-password", class: "form-control"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:password_confirmation)}
      = f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control"
  .col-sm-6.pb-3
    label.pb-2 #{Staff.human_attribute_name(:role)}
    = f.select :role, options_for_select(Staff.roles.keys.map { |k| [I18n.t("enums.staff.role.#{k}"), k] }, f.object.role), {}, {class: 'form-select'}
  .col-sm-6.pb-3
    label.pb-2 移動時間バッファ (単位:分)
    = f.text_field :buffer_time, class: 'form-control', type: "number"

  - unless f.object.new_record?
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:phone)}
      span.text-danger.ms-2 ※「-」無しで記入してください
      = f.text_field :phone, class: "form-control", pattern: "^[0-9]+$"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:gender)}
      = f.select :gender, options_for_select(Staff.genders.keys.map { |k| [I18n.t("enums.staff.gender.#{k}"), k] }, f.object.gender), {}, {class: 'form-select'}
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:birthday)}
      = f.date_field :birthday, class: "form-control", maxlength: "10", size: "10", step: "1"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:postal_code)}
      span.text-danger.ms-2 ※「-」無しで記入してください
      = f.text_field :postal_code, class: "form-control", pattern: "^[0-9]+$", onkeyup: "AjaxZip3.zip2addr(this,'','staff[prefecture]','staff[address]');", placeholder: "例:8100000"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:prefecture)}
      = f.text_field :prefecture, class: "form-control"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:address)}
      = f.text_field :address, class: "form-control"
    .col-sm-6.pb-3
      label.pb-2 #{Staff.human_attribute_name(:hobby)}
      = f.text_field :hobby, class: "form-control"
    .col-sm-8.pb-3
      label.pb-2 #{Staff.human_attribute_name(:memo)}
      = f.text_area :memo, size: "30x10", class: "form-control"

center.pb-4
  = render partial: "components/submit_btn", locals: { f: f }

app/views/staffs/_search.html.slim
#accordionFlushExample.accordion.accordion-flush.shadow.p-1.mb-2.bg-body.rounded.col-sm-6
  .accordion-item
    h2#flush-headingOne.accordion-header
      button.accordion-button.collapsed aria-controls="flush-collapseOne" aria-expanded="false" data-bs-target="#flush-collapseOne" data-bs-toggle="collapse" type="button"
        | 検索
    #flush-collapseOne.accordion-collapse.collapse aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample"
      .accordion-body
        = form_with url: staffs_path, data: { turbo: false }, local: false, method: :get do |f|
          .row.mb-3
            label.col-sm-4.col-form-label.fst-italic スタッフ名
            .col-sm-8
              = f.text_field :name, value: params[:name], class: "form-control", placeholder: "田中 太郎"
          .row.mb-3
            label.col-sm-4.col-form-label.fst-italic 住所
            .col-sm-8
              = f.text_field :address, value: params[:address], class: "form-control", placeholder: "福岡県, 中央区, Sinkawascheビル"
          .row.mb-3
            label.col-sm-4.col-form-label.fst-italic 役職
            .col-sm-8
              = f.select :role, options_for_select(Staff.roles.keys.map { |k| [I18n.t("enums.staff.role.#{k}"), k] }, params[:role]), {include_blank: '選択してください'}, {class: 'form-select'}
          .col-12.d-flex.justify-content-end
            button.btn.btn-outline-primary.mx-1.shadow.rounded-pill.px-4
              |検索
              i.bi.bi-search

app/views/staffs/edit.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-4.d-flex.align-items-center
        .fs-3 スタッフ編集
        = link_to "一覧に戻る", "#{staffs_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }

    = form_with model: @staff, url: staff_path, data: { turbo: false } do |f|
      = render partial: "components/error_messages", locals: { form: f.object }
      = render partial: "form", locals: { f: f }

app/views/staffs/index.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-2.fs-3 スタッフ一覧
      = render partial: "components/edit_btn", locals: { label_name: "スタッフ", path: new_staff_path }

    = render partial: "components/flash_messages"

    = render partial: "search"
    .card.col-sm-12.shadow.p-3.mb-5.bg-body.rounded
      table.table.table-striped.table-sm.mb-5
        thead
          tr
            th.col-sm-2.px-2 = "氏名"
            th.col-sm-2.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "Eメール"
            th.col-sm-2 = "電話番号"
            th.col-sm-3.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "住所"
            th.col-sm-1.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "役職"

        tbody
          - @staffs.each do |staff|
            tr
              td.td_vertical_align_middle.px-2 = staff.full_name
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = staff.email
              td.td_vertical_align_middle = staff.phone
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = staff.full_address.truncate(20)
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = staff.role_i18n
              td.td_vertical_align_middle
                .btn-group.dropstart.d-flex.flex-row-reverse.px-1
                  span.bi.bi-three-dots aria-expanded="false" data-bs-toggle="dropdown" type="button"  style="color: #black; font-size: 20px"
                  ul.dropdown-menu
                    li
                      = link_to "閲覧", "#{staff_path(staff.id)}", { method: :get, class: "dropdown-item" }
                    li
                      = link_to "シフト", "#{staff_calendar_staff_shifts_path(staff_id: staff.id)}", { method: :get, class: "dropdown-item" }
                    li
                      = link_to "編集する", "#{edit_staff_path(staff.id)}", { method: :get, class: "dropdown-item", data: { turbo: false } }
                    - if staff&.reservations.blank? && current_staff.admin?
                      li
                        = button_to "削除", "#{staff_path(staff.id)}", { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" }}, class: "dropdown-item" }

    = paginate @staffs, theme: 'bootstrap-5'

app/views/staffs/new.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-4.d-flex.align-items-center
        .fs-3 スタッフ新規作成
        = link_to "一覧に戻る", "#{staffs_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }

    = form_with model: @staff, url: create_account_staffs_path(@staff), data: { turbo: false }, local: false do |f|
      = render partial: "components/error_messages", locals: { form: f.object }
      = render partial: "form", locals: { f: f }

app/views/staffs/show.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-2.d-flex.align-items-center
        .fs-3 スタッフ詳細
        = link_to "一覧に戻る", "#{staffs_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }
      .btn-toolbar.mb-2.mb-md-0.d-none.d-sm-flex
        = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_staff_path(@staff.id) }
        - if @staff&.reservations.blank? && current_staff&.admin?
          = render partial: "components/delete_btn", locals: { path: staff_path(@staff.id) }

    .card.col-sm-12.shadow.p-3.mb-3.bg-body.rounded
      .card-body
        .row
          .col-5.col-sm-2
            | 名前
          .col-7.col-sm-10.fw-bold
            | #{@staff.full_name.presence || "-"}

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:gender)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.gender_i18n.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:email)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.email.presence || "-"}

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:role)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.role_i18n.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | 移動時間バッファ (単位:分)
          .col-7.col-sm-10.fw-bold
            | #{@staff.buffer_time.presence || "-"}分

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:phone)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.phone.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:gender)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.gender_i18n.presence || "-"}

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:birthday)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.birthday.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:postal_code)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.postal_code.presence || "-"}

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:prefecture)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.prefecture.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:address)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.address.presence || "-"}

      .card-body style="background:#EEEEEE;"
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:hobby)}
          .col-7.col-sm-10.fw-bold
            | #{@staff.hobby.presence || "-"}

      .card-body
        .row
          .col-5.col-sm-2
            | #{Staff.human_attribute_name(:memo)}
          .col-7.col-sm-10.fw-bold
            | #{simple_format(@staff.memo).presence || "-"}

    .container
      .row.mb-3
        - if @staff&.reservations.present?
          center
            = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_staff_path(@staff.id) }
        - else
          .col-sm-6.col-md-6.col-6 style="text-align: right;"
            = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_staff_path(@staff.id) }
          - if current_staff&.admin?
            .col-sm-6.col-md-6.col-6
              = render partial: "components/delete_btn", locals: { path: staff_path(@staff.id) }