config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  post "/login", to: "sessions#login"
  # 打鍵して不要であれば削除
  # post "/request_change_login", to: "sessions#request_change_login"

  get "/forgot_password", to: "sessions#forgot_password"
  post "/send_reset_password_email", to: "sessions#send_reset_password_email"
  get "/:token/new_password", to: "sessions#new_password", as: "new_password"
  post "/reset_password", to: "sessions#reset_password"

  # キャンセル依頼トップ
  get "/forms/request_change_top", to: "forms#request_change_top"
  # キャンセル依頼ログイン
  post "/forms/request_change_login", to: "forms#request_change_login"
  # キャンセル依頼コンタクト送信フォーム
  get "/forms/request_change_contact", to: "forms#request_change_contact"
  # キャンセル依頼POST
  post "/forms/creation_request_change", to: "forms#creation_request_change"


  get "/forms/top", to: "forms#top"
  get "/forms/select_working_location", to: "forms#select_working_location"
  post "/forms/register_working_location", to: "forms#register_working_location"
  post "/forms/destroy_working_location", to: "forms#destroy_working_location"
  get "/forms/select_menu", to: "forms#select_menu"
  get "/forms/select_day", to: "forms#select_day"
  get "/forms/select_time", to: "forms#select_time"
  get "/forms/input_info", to: "forms#input_info"
  get "/forms/confirm", to: "forms#confirm"
  get "/forms/success", to: "forms#success"
  get "/forms/help", to: "forms#help"
  post "/forms/apply_reservation", to: "forms#apply_reservation"
  get "/", to: "reservations#index"
  devise_for :staffs, controllers: {
    sessions: "staffs/sessions",
    registrations: "staffs/registrations",
    passwords: "staffs/passwords"
  }
  devise_scope :staff do
    get "/staffs/sign_out" => "devise/sessions#destroy"
  end

  resources :staffs do
    post "create_account", on: :collection
  end
  resources :travel_fees
  resources :car_wash_menus do
    get "copy", on: :member
  end
  resources :car_wash_options do
    get "copy", on: :member
    get :search, on: :collection
  end
  resources :reservations do
    post "/send_email", to: "reservations#send_email", on: :member
    get "/request_read", to: "reservations#request_read", on: :member
  end
  resources :customers
  resources :working_locations
  resources :staff_shifts do
    get "/", to: "staff_shifts#calendar", on: :collection
    get "/staff_calendar", to: "staff_shifts#staff_calendar", on: :collection
    get "/bulk_input", to: "staff_shifts#bulk_input", on: :collection
    get "/bulk_chenge_input", to: "staff_shifts#bulk_chenge_input", on: :collection
    post "/bulk_register", to: "staff_shifts#bulk_register", on: :collection
  end

  namespace :api do
    get "staff_shift_model_list", to: "staff_shifts#staff_shift_model_list"
    get "car_size_list", to: "select_menus#car_size_list"
    get "car_maker_list", to: "select_menus#car_maker_list"
    get "car_model_list", to: "select_menus#car_model_list"
    get "menu_and_option_list", to: "select_menus#menu_and_option_list"
    get "working_location", to: "select_menus#working_location"
    get "assignable_staff_list", to: "select_menus#assignable_staff_list"
  end
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  include Discard::Model
  include Request::RequestGeo
  has_secure_password validations: false

  has_many :working_locations
  has_many :reservations

  before_validation :set_lon_lat

  validates :family_name, presence: true
  validates :name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "はカタカナで入力して下さい。" }
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "はカタカナで入力して下さい。" }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates_uniqueness_of :email, conditions: -> { where(discarded_at: nil) }
  validates :prefecture, presence: true
  validates :address_first, presence: true
  validates :address_second, presence: true
  validates :aware_route, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  validates :phone, presence: true
  validates_uniqueness_of :phone, conditions: -> { where(discarded_at: nil) }
  validate :phone_number_check?
  validates :postal_code, presence: true
  validate :postal_code_check?

  enum aware_route: { home_page: "home_page", flyer: "flyer", review: "review", introduction: "introduction", other: "other" }

  def create_reset_digest
    self.reset_token = Customer.new_token
    update_attribute(:reset_digest,  Customer.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    CustomerMailer.reset_password(self).deliver_now
  end

  # welcomeメールを送信する
  def send_welcome_email
    CustomerMailer.welcome(self).deliver_now
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(reset_token)
    return false if reset_digest.nil?
    BCrypt::Password.new(reset_digest).is_password?(reset_token)
  end

  def full_name
    "#{family_name} #{name}"
  end

  def full_name_kana
    "#{family_name_kana} #{name_kana}"
  end

  def full_address
    "#{prefecture} #{address_first} #{address_second} #{building}"
  end

  def check_have_reservation
    errors.add(:base, "予約に紐づいているため、削除できません") if reservations.present?
  end

  def creation_working_location
    self.working_locations.build(
      postal_code: self.postal_code,
      prefecture: self.prefecture,
      address_first: self.address_first,
      address_second: self.address_second,
      building:  self.building
    )
    self.save
  end

  private
    def phone_number_check?
      return true if phone.blank?
      return errors.add(:phone, ": -(ハイフン)は入れないでください") if phone.match?(/[-]/)
      return errors.add(:phone, ": 10または11桁にしてください") unless phone.match?(/\A\d{10,11}\z/)
    end

    def postal_code_check?
      return true if postal_code.blank?
      return errors.add(:postal_code, ": -(ハイフン)は入れないでください") if postal_code.match?(/[-]/)
      return errors.add(:postal_code, ": 7桁にしてください") unless postal_code.match?(/\A\d{7}\z/)
    end

    def set_lon_lat
      return unless postal_code_changed?
      self.longitude, self.latitude = get_geo(postal_code).values
    end

    def self.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  before_action :authenticate_staff!
  before_action :authenticate_role_admin!

  def index
    customers = search_index(params)
    @customers = customers.order(created_at: "desc").page(params[:page]).per(30)
  end

  def show
    @customer = Customer.find_by(id: params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    params[:customer][:password] = params[:customer][:email]
    @customer = Customer.new(customer_params)
    begin
      @customer.creation_working_location
      if @customer.save
        @customer.create_reset_digest
        @customer.send_welcome_email
        flash[:notice] = "お客様情報を作成しました。"
        redirect_to customers_path
      else
        render "new"
      end
    rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError, ActiveRecord::RecordInvalid => e
      Rails.logger.error("メール送信に失敗しました。システム担当者にご連絡ください。 #{e.message}")
      redirect_to customers_path, flash: { error: "メール送信に失敗しました。システム担当者にご連絡ください。 #{e.message}" }
    end
  end

  def edit
    @customer = Customer.find_by(id: params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "お客様情報を更新しました"
      redirect_to customers_path
    else
      render "edit"
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.check_have_reservation
    if @customer.errors.blank? && @customer.discard
      flash[:notice] = "お客様情報を削除しました"
      redirect_to customers_path
    else
      errors = @customer.errors.full_messages
      errors.unshift("お客様情報を削除できませんでした。")
      flash[:errors] = errors
      redirect_to customers_path
    end
  end

  private
    def search_index(params)
      customer_ids = []
      customer_ids << Reservation.where("start_at >= ?", "#{params[:start_day].to_datetime.beginning_of_day}").pluck(:customer_id) if params[:start_day].present?
      customer_ids << Reservation.where("end_at <= ?", "#{params[:end_day].to_datetime.end_of_day}").pluck(:customer_id) if params[:end_day].present?
      customers = customer_ids.present? ? Customer.where(id: customer_ids&.uniq) : Customer.all
      params[:name]&.gsub("　", " ")&.split(" ")&.map do |str|
        customers = customers.where("family_name LIKE ?", "%#{str}%").or(customers.where("name LIKE ?", "%#{str}%"))
      end
      customers = customers.where(notice: true) if params[:public].eql?("1")
      customers = customers.where(notice: false) if params[:private].eql?("1")
      customers = customers.where(aware_route: params[:aware_route]) if params[:aware_route].present?
      # 住所あいまい検索
      params[:address]&.gsub(" ", ",")&.gsub("　", ",")&.gsub("、", ",")&.split(",")&.map do |str|
        customers = customers.where("prefecture LIKE ?", "%#{str}%").or(customers.where("address_first LIKE ?", "%#{str}%")).or(customers.where("building LIKE ?", "%#{str}%"))
      end

      customers
    end

    def customer_params
      params.require(:customer)
      .permit(
        :family_name, :name, :family_name_kana, :name_kana, :email, :password,
        :phone, :postal_code, :prefecture, :address_first, :address_second, :building, :memo, :aware_route,
        :latitude, :longitude, :notice, :reset_token, :reset_sent_at, :reset_digest
      )
    end
end

app/views/customers/_form.html.slim
script[src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"]
.card.col-sm-12.shadow.p-3.mb-5.bg-body.rounded
  .row.g-1.col-sm-12.col-md-12.col-lg-6
    .col.col-sm-6.pb-2
      label.pb-2  #{Customer.human_attribute_name(:family_name)}
      = f.text_field :family_name, class: "form-control"
    .col.col-sm-6.pb-2
      label.pb-2  #{Customer.human_attribute_name(:name)}
      = f.text_field :name, class: "form-control"
  .row.g-1.col-sm-12.col-md-12.col-lg-6
    .col.col-sm-6.pb-2
      label.pb-2  #{Customer.human_attribute_name(:family_name_kana)}
      = f.text_field :family_name_kana, class: "form-control"
    .col.col-sm-6.pb-2
      label.pb-2  #{Customer.human_attribute_name(:name_kana)}
      = f.text_field :name_kana, class: "form-control"
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:email)}
    = f.text_field :email, class: "form-control"
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:phone)}
    span.text-danger.ms-2 ※「-」無しで記入してください
    = f.text_field :phone, class: "form-control", pattern: "^[0-9]+$"
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:postal_code)}
    span.text-danger.ms-2 ※「-」無しで記入してください
    = f.text_field :postal_code, class: "form-control", pattern: "^[0-9]+$", onkeyup: "AjaxZip3.zip2addr(this,'','customer[prefecture]','customer[address_first]');", placeholder: "例:8100000"
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:prefecture)}
    = f.text_field :prefecture, class: "form-control", readonly: true
  .col-sm-6.pb-2
    label.pb-2  市区町村
    = f.text_field :address_first, class: "form-control", value: f.object.address_first, readonly: true
  .col-sm-6.pb-2
    label.pb-2  番地以下
    span.text-danger.ms-2 ※必須 (「-」以外の記号は利用できません)
    = f.text_field :address_second, class: "form-control", value: f.object.address_second
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:building)}
    = f.text_field :building, class: "form-control"
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:aware_route)}
    = f.select :aware_route, options_for_select(Customer.aware_routes.keys.map { |k| [I18n.t("enums.customer.aware_route.#{k}"), k] }, f.object.aware_route), {}, {class: 'form-select'}
  .col-sm-6.pb-2
    label.pb-2  #{Customer.human_attribute_name(:notice)}
    .form-check.px-3
      .form-switch
        = f.check_box :notice, style: "transform: scale(2);", class: "form-check-input"
  .col-sm-8.pb-2
    label.pb-2  #{Customer.human_attribute_name(:memo)}
    = f.text_area :memo, class: "form-control", size: "30x10", class: "form-control"

center.pb-5
  = render partial: "components/submit_btn", locals: { f: f }

app/views/customers/_search.html.slim
#accordionFlushExample.accordion.accordion-flush.shadow.p-1.mb-2.bg-body.rounded.col-sm-6
  .accordion-item
    h2#flush-headingOne.accordion-header
      button.accordion-button.collapsed aria-controls="flush-collapseOne" aria-expanded="false" data-bs-target="#flush-collapseOne" data-bs-toggle="collapse" type="button"
        | 検索
    #flush-collapseOne.accordion-collapse.collapse aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample"
      .accordion-body
        = form_with url: customers_path, data: { turbo: false }, local: false, method: :get do |f|
          .row.mb-3
            label.col-sm-2.col-form-label.fst-italic お名前
            .col-sm-10
              = f.text_field :name, value: params[:name], class: "form-control", placeholder: "田中 太郎"
          .row.mb-3
            label.col-sm-2.col-form-label.fst-italic 住所
            .col-sm-10
              = f.text_field :address, value: params[:address], class: "form-control", placeholder: "鹿児島県, 鹿児島市, Sinkawascheビル"
          .row.mb-3
            label.col-form-label.fst-italic 直近の予約日付
            .col-5.col-mb-auto
              = f.date_field :start_day, value: params[:start_day], class: "form-control"
            .col-auto.fs-5.p-1.text-black-50 〜
            .col-5.col-mb-auto
              = f.date_field :end_day, value: params[:end_day], class: "form-control"
          .row.mb-3
            label.col-sm-2.col-form-label.fst-italic 認知経路
            .col-sm-3
              = f.select :aware_route, options_for_select(Customer.aware_routes.keys.map { |k| [I18n.t("enums.customer.aware_route.#{k}"), k] }, params[:aware_route].presence), {include_blank: ""}, {class: 'form-select'}
          .row.mb-3.mx-1
            label.col-form-label.fst-italic お知らせ
            .col-sm-2.form-check
              = f.check_box :public, value: "", style: "", class: "form-check-input", checked: params[:public].present? ? params[:public].eql?("1") : false
              label.form-check-label.fst-italic for="flexRadioDefault1" 有
            .col-sm-3.form-check
              = f.check_box :private, value: "", style: "", class: "form-check-input", checked: params[:private].present? ? params[:private].eql?("1") : false
              label.form-check-label.fst-italic for="flexRadioDefault2" 無
          .col-12.d-flex.justify-content-end
            button.btn.btn-outline-primary.mx-1.shadow.rounded-pill.px-4
              |検索
              i.bi.bi-search

app/views/customers/edit.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-4.d-flex.align-items-center
        .fs-3 お客様情報 編集
        = link_to "一覧に戻る", "#{customers_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }

    = form_with model: @customer, url: customer_path, data: { turbo: false } do |f|
      = render partial: "components/error_messages", locals: { form: f.object }
      = render partial: "form", locals: { f: f }

app/views/customers/index.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-2.fs-3 お客様情報一覧
      = render partial: "components/new_btn", locals: { label_name: "お客様", path: new_customer_path }
    = render partial: "components/flash_messages"

    = render partial: "search"
    .card.col-sm-12.shadow.p-3.mb-5.bg-body.rounded.small
      table.table.table-striped.table-sm.mb-3
        thead
          tr
            th.col-sm-1.px-2 = "氏名"
            th.col-sm-1 = "電話"
            th.col-sm-3.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "住所"
            th.col-sm-2.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "Eメール"
            th.col-sm-2.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "認識ルート"
            th.col-sm-1.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = "お知らせ"

        tbody
          - @customers.each do |customer|
            tr
              td.td_vertical_align_middle.px-2 = customer.full_name
              td.td_vertical_align_middle = customer.phone
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = customer.full_address.truncate(20)
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = customer.email
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = customer.aware_route.present? ? Customer.aware_routes_i18n[customer.aware_route] : "-"
              td.td_vertical_align_middle.d-none.d-sm-table-cell.d-md-table-cell.d-lg-table-cell.d-xl-table-cell.d-xxl-table-cell = customer.notice.present? ? "有" : "無"
              td.td_vertical_align_middle
                .btn-group.dropstart.d-flex.flex-row-reverse.px-1
                  span.bi.bi-three-dots aria-expanded="false" data-bs-toggle="dropdown" type="button"  style="color: #black; font-size: 20px"
                  ul.dropdown-menu
                    li
                      = link_to "閲覧", "#{customer_path(customer.id)}", { method: :get, class: "dropdown-item" }
                    li
                      = link_to "予約確認", "#{reservations_path(customer_id: customer.id)}", { method: :get, class: "dropdown-item" }
                    li
                      = link_to "予約作成", "#{new_reservation_path(customer_id: customer.id)}", { method: :get, class: "dropdown-item" }
                    li
                      = link_to "編集する", "#{edit_customer_path(customer.id)}", { method: :get, class: "dropdown-item", data: { turbo: false } }
                    - unless customer&.reservations.present?
                      li
                        = button_to "削除", "#{customer_path(customer.id)}", { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" }}, class: "dropdown-item" }

    = paginate @customers, theme: 'bootstrap-5'

app/views/customers/new.html.slim
main
  .col-12.col-md-11.m-auto
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-4.d-flex.align-items-center
        .fs-3 お客様情報 新規作成
        = link_to "一覧に戻る", "#{customers_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }

    = form_with model: @customer, url: customers_path, data: { turbo: false }, local: false do |f|
      = render partial: "components/error_messages", locals: { form: f.object }
      = render partial: "form", locals: { f: f }

app/views/customers/show.html.slim
main
  .col-12.col-md-11.m-auto.mb-5
    .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.mt-5.mb-2.border-bottom.border-4
      .ps-2.d-flex.align-items-center
        .fs-3 お客様詳細
        = link_to "一覧に戻る", "#{customers_path}", { method: :index, class: "bi bi-chevron-left ps-4 pt-2" }
      .btn-toolbar.mb-2.mb-md-0.d-none.d-sm-flex
        = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_customer_path(@customer.id) }
        - unless @customer&.reservations.present?
          = render partial: "components/delete_btn", locals: { path: customer_path(@customer.id) }
    = render partial: "components/flash_messages"
  .container
    .row
      .col-lg-7
        .card.col-sm-12.shadow.p-3.mb-3.bg-body.rounded
          .card-body
            .row
              .col-5.col-sm-2
                | 名前
              .col-7.col-sm-10.fw-bold
                | #{@customer.full_name.presence || "-"}
          .card-body style="background:#EEEEEE;"
            .row
              .col-5.col-sm-2
                | フリガナ
              .col-7.col-sm-10.fw-bold
                | #{@customer.full_name_kana.presence || "-"}

          .card-body
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:email)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.email.presence || "-"}

          .card-body style="background:#EEEEEE;"
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:phone)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.phone.presence || "-"}

          .card-body
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:postal_code)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.postal_code.presence || "-"}

          .card-body style="background:#EEEEEE;"
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:prefecture)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.prefecture.presence || "-"}

          .card-body
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:address)}
              .col-7.col-sm-10.fw-bold
                | #{(@customer.address_first + " " + @customer.address_second).presence || "-"}

          .card-body style="background:#EEEEEE;"
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:building)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.building.presence || "-"}

          .card-body
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:memo)}
              .col-7.col-sm-10.fw-bold
                | #{simple_format(@customer.memo).presence || "-"}

          .card-body style="background:#EEEEEE;"
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:aware_route)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.aware_route.present? ? Customer.aware_routes_i18n[@customer.aware_route] : "-"}

          .card-body
            .row
              .col-5.col-sm-2
                | #{Customer.human_attribute_name(:notice)}
              .col-7.col-sm-10.fw-bold
                | #{@customer.notice.present? ? "有" : "無"}
        .container
          .row.mb-3
              - if @customer&.reservations.present?
                center
                  = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_customer_path(@customer.id) }
              - else
                .col-sm-6.col-md-6.col-6 style="text-align: right;"
                  = render partial: "components/edit_btn", locals: { label_name: "編集する", path: edit_customer_path(@customer.id) }
                .col-sm-6.col-md-6.col-6
                  = render partial: "components/delete_btn", locals: { path: customer_path(@customer.id) }

      .col-lg-5
        .card.col-sm-12.shadow.mb-3.rounded
          .card-header
            .card-title.text-center.mt-2
              i.bi.bi-pin-map-fill
              span 作業場所
          .card-body
            .d-flex.justify-content-center
              = link_to new_working_location_path(customer_id: @customer.id), class: "button btn btn-outline-secondary rounded col-10 py-4 mb-3 text-decoration-none", style: "border-style: dashed;" do
                .text-dark.small
                  i.bi.bi-plus-square-dotted.pl-1.mx-1
                  | 新しい住所
            .col-12
              - @customer.working_locations.sort_by{|val| val.updated_at }.reverse.each do |wl|
                .row.border.shadow.rounded.col-10.pt-4.mb-3.mx-auto
                  p.m-0.text-dark.small.text-start.px-4
                    | #{wl.postal_code}
                  p.m-0.text-dark.small.text-start.px-4
                    | #{wl.full_address}
                  .row.col-12.text-right.mx-3.mt-4.mb-1
                    .col-11.d-flex.justify-content-end
                      = link_to edit_working_location_path(wl.id, customer_id: @customer.id), class: "text-decoration-none me-2" do
                        .text-dark.small
                          i.bi.bi-pencil-square
                          | 編集
                      = link_to working_location_path(wl.id), data: { turbo_method: :delete }, class: "text-decoration-none" do
                        .text-dark.small
                          i.bi.bi-trash
                          | 削除