config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  post "/login", to: "sessions#login"
  # 打鍵して不要であれば削除
  # post "/request_change_login", to: "sessions#request_change_login"

  get "/forgot_password", to: "sessions#forgot_password"
  post "/send_reset_password_email", to: "sessions#send_reset_password_email"
  get "/:token/new_password", to: "sessions#new_password", as: "new_password"
  post "/reset_password", to: "sessions#reset_password"

  # キャンセル依頼トップ
  get "/forms/request_change_top", to: "forms#request_change_top"
  # キャンセル依頼ログイン
  post "/forms/request_change_login", to: "forms#request_change_login"
  # キャンセル依頼コンタクト送信フォーム
  get "/forms/request_change_contact", to: "forms#request_change_contact"
  # キャンセル依頼POST
  post "/forms/creation_request_change", to: "forms#creation_request_change"


  get "/forms/top", to: "forms#top"
  get "/forms/select_working_location", to: "forms#select_working_location"
  post "/forms/register_working_location", to: "forms#register_working_location"
  post "/forms/destroy_working_location", to: "forms#destroy_working_location"
  get "/forms/select_menu", to: "forms#select_menu"
  get "/forms/select_day", to: "forms#select_day"
  get "/forms/select_time", to: "forms#select_time"
  get "/forms/input_info", to: "forms#input_info"
  get "/forms/confirm", to: "forms#confirm"
  get "/forms/success", to: "forms#success"
  get "/forms/help", to: "forms#help"
  post "/forms/apply_reservation", to: "forms#apply_reservation"
  get "/", to: "reservations#index"
  devise_for :staffs, controllers: {
    sessions: "staffs/sessions",
    registrations: "staffs/registrations",
    passwords: "staffs/passwords"
  }
  devise_scope :staff do
    get "/staffs/sign_out" => "devise/sessions#destroy"
  end

  resources :staffs do
    post "create_account", on: :collection
  end
  resources :travel_fees
  resources :car_wash_menus do
    get "copy", on: :member
  end
  resources :car_wash_options do
    get "copy", on: :member
    get :search, on: :collection
  end
  resources :reservations do
    post "/send_email", to: "reservations#send_email", on: :member
    get "/request_read", to: "reservations#request_read", on: :member
  end
  resources :customers
  resources :working_locations
  resources :staff_shifts do
    get "/", to: "staff_shifts#calendar", on: :collection
    get "/staff_calendar", to: "staff_shifts#staff_calendar", on: :collection
    get "/bulk_input", to: "staff_shifts#bulk_input", on: :collection
    get "/bulk_chenge_input", to: "staff_shifts#bulk_chenge_input", on: :collection
    post "/bulk_register", to: "staff_shifts#bulk_register", on: :collection
  end

  namespace :api do
    get "staff_shift_model_list", to: "staff_shifts#staff_shift_model_list"
    get "car_size_list", to: "select_menus#car_size_list"
    get "car_maker_list", to: "select_menus#car_maker_list"
    get "car_model_list", to: "select_menus#car_model_list"
    get "menu_and_option_list", to: "select_menus#menu_and_option_list"
    get "working_location", to: "select_menus#working_location"
    get "assignable_staff_list", to: "select_menus#assignable_staff_list"
  end
end

app/models/car_size.rb
# frozen_string_literal: true

class CarSize < ApplicationRecord
  include Discard::Model

  has_one :reservation_info
  has_many :car_wash_options
  validates :name, presence: true
  validates :memo, presence: true

  # def check_have_menu_and_options
  #   return if discarded_at.nil?
  #   errors.add(:base, "洗車メニューに紐づいているため、削除できません") if car_wash_menus.present?
  #   errors.add(:base, "洗車オプションに紐づいているため、削除できません") if car_wash_menus.present?
  # end
end

app/controllers/forms_controller.rb
# frozen_string_literal: true

class FormsController < ApplicationController
  include Request::RequestGeo
  layout "customer_form"
  before_action :set_session, only: [:select_menu, :select_day, :select_time, :input_info, :confirm]
  before_action :valid_to_have_session, only: [:select_day, :select_time, :input_info, :confirm]

  # 変更依頼トップ
  def request_change_top
    @reservation_id = params[:reservation_id]
    flash.now[:error] = "パスワードが正しくありません。" if params[:pas_error].present?
  end

  # 変更依頼ログイン
  def request_change_login
    redirect_to forms_request_change_top_path(reservation_id: params[:reservation_id], pas_error: true) and return unless Reservation.find_by(id: params[:reservation_id])&.customer.authenticate(params[:password])
    @customer = current_customer
    redirect_to forms_request_change_contact_path(customer: @customer, reservation_id: params[:reservation_id])
  end

  # 変更依頼フォーム
  def request_change_contact
    @customer = current_customer
  end

  # 変更依頼作成
  def creation_request_change
    @customer = current_customer
    if params[:reservation_type] == "cancel" && params[:cancel_memo].blank? || params[:reservation_type] == "change" && params[:change_memo].blank?
      flash.now[:errors] = []
      flash.now[:errors] << "キャンセル理由を入力してください。" if params[:reservation_type] == "cancel" && params[:cancel_memo].blank?
      flash.now[:errors] << "変更理由を入力してください。" if params[:reservation_type] == "change" && params[:change_memo].blank?
      render "request_change_contact"
    else
      request_change = RequestChange.new(
        reservation_id: params[:reservation_id],
        reservation_type: params[:reservation_type],
        memo: params[:cancel_memo].presence || params[:change_memo]
      )
      request_change.save
      flash[:notice] = "変更依頼が完了しました。＊変更またはキャンセルできない場合がございます。"
      ReservationMailer.change(request_change).deliver_now
      redirect_to forms_request_change_top_path(reservation_id: params[:reservation_id])
    end
  end

  def select_working_location
    @customer = current_customer
    @current_step = 0
  end

  def register_working_location
    @customer = current_customer
    @working_location = params[:working_location][:id] == "new" ? WorkingLocation.new : WorkingLocation.find_by(id: params[:working_location][:id])
    if @working_location.update(register_working_location_attributes)
      redirect_to forms_select_working_location_path, flash: { notice: "作業場所情報の保存に成功しました。" }
    else
      errors = @working_location.errors&.full_messages
      errors.unshift("作業場所情報の保存に失敗しました。")
      flash.now[:errors] = errors
      render :select_working_location
    end
  end

  def destroy_working_location
    @working_location = WorkingLocation.find_or_initialize_by(id: params[:working_location_id])
    @working_location.discard
    redirect_to forms_select_working_location_path
  end

  def help
  end

  def top
    massage = flash[:error]
    reset_session
    flash.now[:error] = massage
  end

  def select_menu
    @customer = current_customer
    if current_customer.present? && params[:w_id].blank? && session[:w_id].blank?
      redirect_to forms_select_working_location_path
    else
      initialize_session if current_customer.present?
      @current_step = 1
    end
  end

  def select_day
    if params[:start_date].present? && params[:start_date].to_date >= (Time.current + 3.months).end_of_month
      params[:start_date] = (Time.current.to_date + 3.months).to_s
      flash[:error] = "三ヶ月より先の予約はできません。"
    elsif params[:start_date].present? && params[:start_date].to_date.end_of_month < Time.current.beginning_of_month
      params[:start_date] = Time.current.to_date.to_s
      flash[:error] = "過去のカレンダーは閲覧できません"
    end

    if params[:reservation].present?
      data = params[:reservation].permit!
      flash.now[:errors] = []
      data.to_h.values.map { |val| (val["car_model_name"].presence || val["car_maker_id"].presence && val["car_model_id"]).blank? }.each.with_index(1) do |empty, i|
        flash.now[:errors] << "#{i}台目の車種を選択または、車種名を入力ください" if empty
      end
      if flash.now[:errors].present?
        @current_step = 1
        render "select_menu"
      end
    end

    @current_step = 2
  end

  def select_time
    redirect_to forms_select_day_path, flash: { error: "#{params[:day].to_date.strftime("%m月%d日")}に空き枠がありませんでした。日付選択からやり直してください。" } unless session[:time_schedule].map { |sche| sche.second.present? }.include?(true)

    @current_step = 3
  end

  def input_info
    @current_step = 4
  end

  def confirm
    @reservation = Reservation.new(reservation_attributes)
    if @reservation.staff.blank? # 担当できるスタッフが存在しない
      redirect_to forms_select_day_path, flash: { error: "入力中に予約が埋まってしまいました。日付選択からやり直してください。" }
    else
      @customer = @reservation.customer.presence || @reservation.build_customer
      @customer.assign_attributes(customer_attributes)
      @reservation.build_working_location(working_location_attributes)
      redirect_to forms_input_info_path, flash: { errors: error_full_message } if @customer.invalid? || @reservation.invalid?
    end
    @current_step = 5
  end

  def apply_reservation
    @reservation = Reservation.new(reservation_attributes)
    if @reservation.staff.blank?
      redirect_to forms_select_day_path, flash: { error: "入力中に予約が埋まってしまいました。日付選択からやり直してください。" }
    else
      @customer = @reservation.customer.presence || @reservation.build_customer
      WorkingLocation.find_by(id: session[:w_id]).blank? ? @reservation.build_working_location(working_location_attributes) : @reservation.working_location_id = session[:w_id]
      Reservation.transaction do
        @customer.update!(customer_attributes)
        session[:customer_id] = @customer.id
        @reservation.save!
      end

      ReservationMailer.apply(@reservation).deliver_now && @reservation.update!({ sent_email: true })
      redirect_to forms_success_path(id: @reservation)
    end
  rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError, ActiveRecord::RecordInvalid => e
    error_full_message << e.full_message if e.full_message.present?
    redirect_to forms_top_path, flash: { errors: error_full_message }
  end

  def success
    @reservation = Reservation.find_by(id: params[:id])
    @customer = @reservation.customer
    if current_customer.blank? || current_customer.id != @customer.id
      reset_session
      redirect_to forms_top_path, flash: { error: "不正な遷移です。初めからやり直して下さい" }, data: { turbo: false }
    else
      reset_session
    end
  end

  private
    def set_session
      set_session_for_select_menus
      return if session[:w_postal_code].blank?

      set_session_for_select_day
      set_session_for_select_time
      set_session_for_input_info
    end

    def calculate_required_time
      minutes = []
      session[:select_menus].map do |menu|
        minutes << CarWashMenu.find_by(id: menu[:car_wash_menu_id])&.required_time
        minutes << CarWashOption.where(id: menu[:car_wash_option_ids]&.values&.map { |option| option.values }&.flatten).map(&:required_time).sum
      end
      required_minutes = minutes.sum
      required_minutes
    end

    def calculate_total_price
      price = []
      session[:select_menus].map do |menu|
        price << CarWashMenu.find_by(id: menu[:car_wash_menu_id]).price
        price << CarWashOption.where(id: menu[:car_wash_option_ids]&.values&.map { |option| option.values }&.flatten).map(&:price).sum
      end
      price << session[:travel_fee]&.price.to_i
      price.sum
    end

    # 以下attributes関連
    def reservation_attributes
      staff_id = nil
      Staff.where(id: session[:staff_ids]).map do |staff|
        next if staff_id.present?
        staff = staff.available(session[:start_at], session[:required_time].minutes, session[:w_postal_code])

        staff_id = staff.id if staff.present?
      end

      result = {
        customer: current_customer,
        start_at: session[:start_at],
        memo: session[:memo],
        total_price: session[:total_price],
        travel_fee: session[:travel_fee]&.price
      }
      result.store(:reservation_infos_attributes, reservation_infos_attributes) if reservation_infos_attributes.present?
      result.store(:staff_id, staff_id) if staff_id.present?
      result
    end

    def reservation_infos_attributes
      session[:select_menus]&.map do |menu|
          car_wash_option_ids = menu[:car_wash_option_ids]&.values&.map { |option| option.values }&.flatten
          return_hash = {
            car_size_id: menu[:car_size_id],
            car_model_name: menu[:car_model_name].presence || CarModel.find(menu[:car_model_id]).name,
            car_wash_menu_id: menu[:car_wash_menu_id]
          }
          if car_wash_option_ids.present?
            option_hash = {
              reservation_car_wash_options_attributes: car_wash_option_ids.filter_map { |option_id|
                { car_wash_option_id: option_id }
              }
            }
            return_hash.merge!(option_hash)
          end
          return_hash
        end
      end

    def working_location_attributes
      {
        customer: @customer,
        postal_code: session[:w_postal_code],
        prefecture: session[:w_prefecture],
        address_first: session[:w_address_1],
        address_second: session[:w_address_2],
        building: session[:w_building]
      }
    end

    def register_working_location_attributes
      params[:working_location][:prefecture], params[:working_location][:address_first] = params["#{params[:working_location][:id]}_prefecture"], params["#{params[:working_location][:id]}_address_first"]
      params.require("working_location").permit(:customer_id, :postal_code, :prefecture, :address_first, :address_second, :building)
    end

    def customer_attributes
      memo = current_customer&.memo.presence || ""
      memo = memo + "\n#{session[:memo]}" if session[:memo].present?
      result = {

app/helpers/forms_helper.rb
# frozen_string_literal: true

module FormsHelper
  def next_step_path(current_step)
    number = current_step.to_i + 1
    page_steps[:"#{number}"]
  end

  def prev_step_path(current_step)
    number = current_step.to_i - 1
    page_steps[:"#{number}"]
  end

  def target_page(number)
    page_steps[:"#{number}"]
  end

  def page_steps
    {
      "0": "/forms/select_working_location",
      "1": "/forms/select_menu",
      "2": "/forms/select_day",
      "3": "/forms/select_time",
      "4": "/forms/input_info",
      "5": "/forms/confirm"
    }
  end
end

app/views/forms/_progress.html.slim
.d-flex.justify-content-center.mt-3.mt-md-5
  .progress.col-11.col-md-8.col-xl-7.rounded style="height: 20px"
    .progress-bar.progress-bar-striped.progress-bar-animated.bg-info.rounded-end style="width: #{value}%" role="progressbar" aria-valuenow="#{value}" aria-valuemin="0" aria-valuemax="100" #{value}%

.d-flex.justify-content-center.mt-3.mt-md-4.mb-3
  i.justify-align-center.bi.bi-card-checklist.fs-4.me-2 style="text-shadow: 1px 1px 2px orange"
  h2.text-dark.fst-italic style="text-shadow: 1px 1px 2px orange" #{text}

app/views/forms/request_change_contact.html.slim
.d-flex.justify-content-center.mt-3.mt-md-4.mb-3
  i.justify-align-center.bi.bi-card-checklist.fs-4.me-2 style="text-shadow: 1px 1px 2px orange"
  h2.text-dark.fst-italic style="text-shadow: 1px 1px 2px orange" 予約変更依頼
= javascript_include_tag "select_menu", "data-turbo-track": "reload", defer: true

.container.justify-content-center.col-11.col-md-10.col-xl-6.mb-5
  = form_with namespace: "reservation", url: forms_creation_request_change_path, data: { turbo: false }, method: :post do |form|
    .js-parentTarget
        .card.shadow.rounded.js-childTarget.mt-1
          .card-header.bg-white.border-bottom.border-info
            .card-title.d-inline-flex.flex-row.align-items-center.mt-2
              i.bi.bi-check2-square.fs-6.text-success.me-1
              span.text-dark.fst-italic.fs-5 style="text-shadow: 1px 1px 2px orange" 変更依頼
          .card-body
            .mb-4
              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                | 変更依頼したい予約選択
                span.text-danger.ms-2 ※必須
              .row.row-cols-1.row-cols-sm-2.row-cols-md-4
                .col-md-4.me-1
                  = form.text_field :reservation_name, value: "#{Reservation.find_by(id: params[:reservation_id]).start_at.strftime('%-m/%d %H:%M')}からの予約", class: "form-control", disabled: "true"
                  = form.hidden_field :reservation_id, value: params[:reservation_id]
            .mb-4
              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                | 変更依頼の種別
                span.text-danger.ms-2 ※必須
              .row.row-cols-1.row-cols-sm-2.row-cols-md-4
                .col-md-4.me-1
                  = form.select :reservation_type, options_for_select(RequestChange.reservation_types.keys.map { |k| [I18n.t("enums.request_change.reservation_type.#{k}"), k] }, params[:status]), {}, {class: 'form-select shadow-sm mt-2 js-changeMaker'}
            .mb-4
              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                | キャンセルする場合はこちらに理由を記入
              .form-group7.mt-2
                = form.text_area :cancel_memo, class: "form-control", value: params[:memo]
            .mb-4
              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                | 変更を依頼する場合はこちらに理由を記入
              .form-group7.mt-2
                = form.text_area :change_memo, class: "form-control", value: params[:memo]

    .row.justify-content-center.mt-3
      button.btn.btn-primary.shadow.rounded.my-2.w-50 name="commit" type="submit" data-turbolinks="false"
        | 送信する

  .row.justify-content-center.mt-3.d-none.d-sm-inline.d-md-inline.d-lg-inline.d-xl-inline.d-xxl-inline
    = link_to "#{forms_request_change_top_path(reservation_id: params[:reservation_id])}", {class: "btn btn-primary shadow rounded-circle text-center d-inline", style: "position: fixed;z-index: 99999;top: 55%;left: 5%;width: 4rem;height:4rem"}, data: { turbo: false } do
      i.bi.bi-arrow-return-left.text-white style="font-size: 2.2rem"
  .row.justify-content-center.mt-3.d-inline.d-sm-none.d-md-none.d-lg-none.d-xl-none.d-xxl-none
    = link_to "#{forms_request_change_top_path(reservation_id: params[:reservation_id])}", {class: "btn btn-primary shadow rounded-circle text-center d-inline", style: "position: fixed;z-index: 99999;top: 55%;left: 2%;width: 3rem;height:3rem"}, data: { turbo: false } do
      i.bi.bi-arrow-return-left.text-white style="font-size: 1.5rem"

app/views/forms/request_change_top.html.slim
.container.mt-md-5.mt-2
  .row.justify-content-center
    .card.col-11.col-md-6.col-xl-4.shadow.rounded-2.mt-md-5
      .card-header.bg-white.text-center
        .mx-auto.mt-3
          i.bi.bi-person-circle.fs-1.text-warning
      .card-body
        = form_with namespace: "reservation", url: forms_request_change_login_path, method: :post do |f|
          .mt-2.mb-2
            label for="inputPassword" class="fst-italic text-dark" Password
            .input-group
              i.input-group-text.bi.bi-key
              = f.password_field :password, name: "password", class: "form-control shadow-sm", id: "inputPassword", required: "true"
              = f.hidden_field :reservation_id, value: @reservation_id
          .mt-4.mb-1.text-center
            button.w-100.btn.btn-lg.btn-outline-primary.btn-block.shadow-sm type="submit"
              i.bi.bi-unlock-fill  Login
          .d-flex.justify-content-end.mt-3
            = link_to "/forgot_password/", { class: "link-secondary" }, data: { turbo: false }
              i.bi.bi-question-circle  Passwordを忘れた方はこちら

app/views/forms/select_working_location.html.slim
script[src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"]
= javascript_include_tag "input_info", "data-turbo-track": "reload", defer: true
= render partial: "progress", locals: { value: 10, text: "作業場所選択" }

.container.justify-content-center.col-11.col-md-10.col-xl-6.mb-5
  .card.shadow.rounded
    .card-body.my-2
      .row.mb-3
        button.btn.btn-outline-secondary.col-10.m-1.p-0.py-3.rounded.mx-auto.py-4 style="border-style: dashed;" type="button" data-bs-toggle="modal" data-bs-target="#sizeModalNew"
          .text-dark.small
            i.bi.bi-plus-square-dotted.pl-1.mx-1
            | 新しい住所
        / formモーダル
        #sizeModalNew.modal.fade[tabindex="-1" aria-labelledby="sizeModalNew" aria-hidden="true"]
          .modal-dialog
            .modal-content
              .modal-body
                button.btn-close.mb-2[type="button" data-bs-dismiss="modal" aria-label="Close"]
                .card
                  .card-header
                    .card-title.my-2 新規作成
                  .card-body
                    = form_for(:working_location, url: forms_register_working_location_path, local: true, data: { turbo: false }) do |form|
                      = form.hidden_field :id, value: "new"
                      = form.hidden_field :customer_id, value: @customer.id
                      .mb-4
                        label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                          | 郵便番号
                        span.text-danger.ms-2 ※必須
                        .form-group.col-md-8
                          = form.text_field :postal_code, class: "form-control", onkeyup: "AjaxZip3.zip2addr( this, '', 'new_prefecture', 'new_address_first');", placeholder: "例:8100000", required: "true"
                      .mb-4
                        label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                          | 都道府県
                        .row.row-cols-1.row-cols-sm-2.row-cols-md-4
                          .form-group.col-md-8
                            = form.text_field :prefecture, class: "form-control", readonly: true, name: "new_prefecture"
                      .mb-4
                        label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                          | 住所
                        .form-group.col-md-8
                          = form.text_field :address_first, class: "form-control", readonly: true, name: "new_address_first"
                      .mb-4
                        label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                          | 番地以下
                        span.text-danger.ms-2 ※必須
                        .form-group.col-md-8
                          = form.text_field :address_second, class: "form-control", required: "true"
                      .mb-4
                        label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                          | 建物
                        .form-group.col-md-8
                          = form.text_field :building, class: "form-control"
                      .row.justify-content-center.mt-3
                        button.btn.btn-primary.shadow.rounded.my-2.w-50 name="commit" type="submit"
                          | 保存
      - @customer.working_locations.sort_by{|val| val.updated_at }.reverse.each do |wl|
        .row.mb-3
          = link_to forms_select_menu_path(w_id: wl.id), class: "text-decoration-none btn btn-outline-secondary border-1 col-10 py-3 px-3 rounded shadow mx-auto" do
            p.m-0.text-dark.small.text-start
              | #{wl.postal_code}
            p.m-0.text-dark.small.text-start
              | #{wl.full_address}
          .row.col-12.mx-auto.text-right
            .col-11.d-flex.justify-content-end
              a.mx-2[type="button" data-bs-toggle="modal" data-bs-target="#formModal#{wl.id}"]
                .text-dark.small
                  i.bi.bi-pencil-square
                  | 変更
              = link_to forms_destroy_working_location_path(working_location_id: wl.id), data: { turbo_method: :post }, class: "text-decoration-none" do
                .text-dark.small
                  i.bi.bi-trash
                  | 削除
              / formモーダル
              .modal.fade[tabindex="-1" aria-labelledby="formModalLabel" aria-hidden="true" id="formModal#{wl.id}"]
                .modal-dialog
                  .modal-content
                    .modal-body
                      button.btn-close.mb-2[type="button" data-bs-dismiss="modal" aria-label="Close"]
                      .card
                        .card-header
                          .card-title.my-2 編集
                        .card-body
                          = form_for(:working_location, url: forms_register_working_location_path, local: true, data: { turbo: false }) do |form|
                            = form.hidden_field :id, value: wl.id 
                            .mb-4
                              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                                | 郵便番号
                              span.text-danger.ms-2 ※必須
                              .form-group.col-md-8
                                = form.text_field :postal_code, class: "form-control", value: wl.postal_code, onkeyup: "AjaxZip3.zip2addr( this, '', '#{wl.id}_prefecture', '#{wl.id}_address_first');", placeholder: "例:8100000", required: "true"
                            .mb-4
                              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                                | 都道府県
                              .row.row-cols-1.row-cols-sm-2.row-cols-md-4
                                .form-group.col-md-8
                                  = form.text_field :prefecture, class: "form-control", value: wl.prefecture, readonly: true, name: "#{wl.id}_prefecture"
                            .mb-4
                              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                                | 住所
                              .form-group.col-md-8
                                = form.text_field :address_first, class: "form-control", value: wl.address_first, readonly: true, name: "#{wl.id}_address_first"
                            .mb-4
                              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                                | 番地以下
                              span.text-danger.ms-2 ※必須
                              .form-group.col-md-8
                                = form.text_field :address_second, class: "form-control", value: wl.address_second, required: "true"
                            .mb-4
                              label.fst-italic.fw-bold.text-dark.border-bottom.border-warning.mb-2
                                | 建物
                              .form-group.col-md-8
                                = form.text_field :building, class: "form-control", value: wl.building
                            .row.justify-content-center.mt-3
                              button.btn.btn-primary.shadow.rounded.my-2.w-50 name="commit" type="submit"
                                | 保存

app/views/forms/top.html.slim
.container.mt-md-5.mt-2
  .row.justify-content-center
    .card.col-11.col-md-6.col-xl-4.shadow.rounded-2.mt-md-5
      .card-header.bg-white.text-center
        .mx-auto.mt-3
          i.bi.bi-person-circle.fs-1.text-warning
      .card-body
        = form_for(:session, url: login_path, local: true, data: { turbo: false }) do |f|
          .mb-2
            label for="inputEmail" class="fst-italic text-dark" Email
            .input-group
              i.input-group-text.bi.bi-envelope
              = f.email_field :email, name: "email", class: "form-control shadow-sm", id: "inputEmail", required: "true", autofocus: "true"
          .mt-2.mb-2
            label for="inputPassword" class="fst-italic text-dark" Password
            .input-group
              i.input-group-text.bi.bi-key
              = f.password_field :password, name: "password", class: "form-control shadow-sm", id: "inputPassword", required: "true"
          .mt-4.mb-1.text-center
            button.w-100.btn.btn-lg.btn-outline-primary.btn-block.shadow-sm type="submit"
              i.bi.bi-unlock-fill  Login
          .d-flex.justify-content-end.mt-3
            = link_to "/forgot_password/", { class: "link-secondary" }, data: { turbo: false }
              i.bi.bi-question-circle  Passwordを忘れた方はこちら
      .card-footer.bg-white.mt-2.mb-2
        .m-auto.mt-2
          = link_to forms_select_menu_path, { class: "text-decoration-none" }, data: { turbo: false }
            button.w-100.btn.btn-lg.btn-outline-primary.btn-block.shadow-sm type="submit"
              i.bi.bi-person-plus
              span.small 初めての予約のお客様

app/views/forms/week.html.slim
.container
  .row
    .col-12.text-center
      h1
        | 予約画面
      p
        | 3ヶ月先まで予約することができます。
    .col-12.mt-3
      = week_calendar events: @reservations do |date, reservations|
        = date.day