config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  post "/login", to: "sessions#login"
  # 打鍵して不要であれば削除
  # post "/request_change_login", to: "sessions#request_change_login"

  get "/forgot_password", to: "sessions#forgot_password"
  post "/send_reset_password_email", to: "sessions#send_reset_password_email"
  get "/:token/new_password", to: "sessions#new_password", as: "new_password"
  post "/reset_password", to: "sessions#reset_password"

  # キャンセル依頼トップ
  get "/forms/request_change_top", to: "forms#request_change_top"
  # キャンセル依頼ログイン
  post "/forms/request_change_login", to: "forms#request_change_login"
  # キャンセル依頼コンタクト送信フォーム
  get "/forms/request_change_contact", to: "forms#request_change_contact"
  # キャンセル依頼POST
  post "/forms/creation_request_change", to: "forms#creation_request_change"


  get "/forms/top", to: "forms#top"
  get "/forms/select_working_location", to: "forms#select_working_location"
  post "/forms/register_working_location", to: "forms#register_working_location"
  post "/forms/destroy_working_location", to: "forms#destroy_working_location"
  get "/forms/select_menu", to: "forms#select_menu"
  get "/forms/select_day", to: "forms#select_day"
  get "/forms/select_time", to: "forms#select_time"
  get "/forms/input_info", to: "forms#input_info"
  get "/forms/confirm", to: "forms#confirm"
  get "/forms/success", to: "forms#success"
  get "/forms/help", to: "forms#help"
  post "/forms/apply_reservation", to: "forms#apply_reservation"
  get "/", to: "reservations#index"
  devise_for :staffs, controllers: {
    sessions: "staffs/sessions",
    registrations: "staffs/registrations",
    passwords: "staffs/passwords"
  }
  devise_scope :staff do
    get "/staffs/sign_out" => "devise/sessions#destroy"
  end

  resources :staffs do
    post "create_account", on: :collection
  end
  resources :travel_fees
  resources :car_wash_menus do
    get "copy", on: :member
  end
  resources :car_wash_options do
    get "copy", on: :member
    get :search, on: :collection
  end
  resources :reservations do
    post "/send_email", to: "reservations#send_email", on: :member
    get "/request_read", to: "reservations#request_read", on: :member
  end
  resources :customers
  resources :working_locations
  resources :staff_shifts do
    get "/", to: "staff_shifts#calendar", on: :collection
    get "/staff_calendar", to: "staff_shifts#staff_calendar", on: :collection
    get "/bulk_input", to: "staff_shifts#bulk_input", on: :collection
    get "/bulk_chenge_input", to: "staff_shifts#bulk_chenge_input", on: :collection
    post "/bulk_register", to: "staff_shifts#bulk_register", on: :collection
  end

  namespace :api do
    get "staff_shift_model_list", to: "staff_shifts#staff_shift_model_list"
    get "car_size_list", to: "select_menus#car_size_list"
    get "car_maker_list", to: "select_menus#car_maker_list"
    get "car_model_list", to: "select_menus#car_model_list"
    get "menu_and_option_list", to: "select_menus#menu_and_option_list"
    get "working_location", to: "select_menus#working_location"
    get "assignable_staff_list", to: "select_menus#assignable_staff_list"
  end
end

app/views/layouts/_header.html.slim
body
  header.navbar.navbar-dark.sticky-top.bg-dark.flex-md-nowrap.p-0.shadow.row style="z-index: 20;"
    .dropdown.col.text-left
      .btn.btn-link.d-inline.d-lg-inline.d-xl-none.d-xxl-none.me-3 aria-expanded="false" data-bs-toggle="dropdown" href="#"
        span.bi.bi-list.text-white style="font-size: 30px"
      ul.dropdown-menu.text-small.shadow.ps-3.pe-1 aria-labelledby="dropdownNavLink"
        .sidebar-heading.d-flex.justify-content-between.align-items-center.px-2.mt-1.mb-1
          span.fs-6 管理
        li
          hr.dropdown-divider
        li
          = render partial: "components/sidebar_link", locals: { label_name: "お客様情報管理", path: "/customers", class_name: "dropdown-item bi bi-file-person-fill" }
        li
          = render partial: "components/sidebar_link", locals: { label_name: "スタッフ管理", path: "/staffs", class_name: "dropdown-item bi bi-person-lines-fill" }
        - if current_staff.admin?
          li
            = render partial: "components/sidebar_link", locals: { label_name: "シフト管理", path: staff_shifts_path(start_date: Date.today.to_s), class_name: "dropdown-item bi bi-layers" }
        - else
          li
            = render partial: "components/sidebar_link", locals: { label_name: "シフト管理", path: staff_calendar_staff_shifts_path(staff_id: current_staff.id), class_name: "dropdown-item bi bi-layers" }
        li
          = render partial: "components/sidebar_link", locals: { label_name: "予約管理", path: "/reservations", class_name: "dropdown-item bi bi-pencil-square" }
        - if current_staff.admin?
          .sidebar-heading.d-flex.justify-content-between.align-items-center.px-2.mt-3.mb-1
            span.fs-6 マスター管理
          li
            hr.dropdown-divider
          li
            = render partial: "components/sidebar_link", locals: { label_name: "オプションマスタ", path: "/car_wash_options", class_name: "dropdown-item bi bi-newspaper" }
          li
            = render partial: "components/sidebar_link", locals: { label_name: "洗車コースマスタ", path: "/car_wash_menus", class_name: "dropdown-item bi bi-stars" }
          li
            = render partial: "components/sidebar_link", locals: { label_name: "出張料金マスタ", path: "/travel_fees", class_name: "dropdown-item bi bi-currency-dollar" }

    .btn.btn-dark.col-lg-2.me-0.px-3.col-6.text-center style="text-align: left;"
      center
        span style="color: #ffc40c; font-weight: 900;" Sinkawasche

    .text-left.col.d-flex.justify-content-end
      .btn-group
        .btn.dropdown-toggle.bg-dark.text-light[type="button" data-bs-toggle="dropdown" aria-expanded="false"]
          i.bi.bi-person-fill.fs-4
        ul.dropdown-menu.dropdown-menu-end
          .sidebar-heading.d-flex.justify-content-between.align-items-center.px-2.mt-1.mb-1
            span.fs-6 #{current_staff.full_name}
          li
            hr.dropdown-divider
          li
            = link_to "ログアウト", destroy_staff_session_path, { method: :delete, class: "dropdown-item", data: { turbo: false } }
          li
            = link_to "スタッフ情報", staff_path(current_staff), { method: :get, class: "dropdown-item", data: { turbo: false } }

app/views/layouts/_sidebar.html.slim
.fixed-top.col-xl-2.bg-warning.vh-100 style="padding-top: 5%; z-index: 10;"
  ul.nav.flex-column.mx-4
    .sidebar-heading.d-flex.justify-content-between.align-items-center.px-2.mt-2.mb-1
      span.fs-5.fw-bold.text-dark 管理
    hr
    li.nav-item
      = render partial: "components/sidebar_link", locals: { label_name: "お客様情報管理", path: "/customers", class_name: "nav-link bi bi-file-person-fill fs-6" }

    li.nav-item
      = render partial: "components/sidebar_link", locals: { label_name: "スタッフ管理", path: "/staffs", class_name: "nav-link bi bi-person-lines-fill fs-6" }

    - if current_staff.staff?
      li.nav-item
        = render partial: "components/sidebar_link", locals: { label_name: "シフト管理", path: staff_calendar_staff_shifts_path(staff_id: current_staff.id), class_name: "nav-link bi bi-layers fs-6" }
    - else
      li.nav-item
        = render partial: "components/sidebar_link", locals: { label_name: "シフト管理", path: staff_shifts_path(start_date: Date.today.to_s), class_name: "nav-link bi bi-layers fs-6" }

  ul.nav.flex-column.mb-2.mx-4
    li.nav-item
      = render partial: "components/sidebar_link", locals: { label_name: "予約管理", path: "/reservations", class_name: "nav-link bi bi-pencil-square fs-6" }

    - if current_staff.admin?
      .sidebar-heading.d-flex.justify-content-between.align-items-center.px-2.mt-4.mb-1
        span.fs-5.fw-bold マスター管理
      hr
      li.nav-item
        = render partial: "components/sidebar_link", locals: { label_name: "洗車コースマスタ", path: "/car_wash_menus", class_name: "nav-link bi bi-newspaper fs-6" }


      li.nav-item
        = render partial: "components/sidebar_link", locals: { label_name: "オプションマスタ", path: "/car_wash_options", class_name: "nav-link bi bi-newspaper fs-6" }

      li.nav-item
        = render partial: "components/sidebar_link", locals: { label_name: "出張料金マスタ", path: "/travel_fees", class_name: "nav-link bi bi-currency-dollar fs-6" }

app/views/layouts/application.html.slim
- if staff_signed_in?
  doctype html
  html.h-100
    head
      title data-turbolinks="false"
        | Sinkawasche
      meta[name="viewport" content="width=device-width,initial-scale=1"]
      = favicon_link_tag "/favicon-car.png"
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag "application"
      = javascript_include_tag "application"
      = javascript_include_tag "admin"

    = render partial: "layouts/header"
    .container-fluid.bg-light
      .row
        .col-xl-2.d-none.d-print-inline.d-sm-none.d-md-none.d-lg-none.d-xl-inline.d-xxl-inline.bg-warning.vh-100
          = render partial: "layouts/sidebar"
        .col-xl-10
          = yield
- else
  doctype html
  html
    head
      title
        | Sinkawasche
      meta[name="viewport" content="width=device-width,initial-scale=1"]
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag "application", "data-turbo-track": "reload"
      = javascript_include_tag "customer_form", "data-turbo-track": "reload", defer: true

      .navbar.navbar-dark.justify-content-center.sticky-top.bg-dark.flex-md-nowrap.p-0.shadow
        span.d-flex.justify-content-center.fs-5.text-warning.fst-italic.col-md-3.col-lg-2.me-0.py-2.px-3 style="text-shadow: 1px 1px orange"
          | Sinkawasche

    body.bg-light
      = render partial: "components/flash_messages"
      = yield

app/views/layouts/customer_form.html.slim
doctype html
html
  head
    title
      | Sinkawasche
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = favicon_link_tag "/favicon-car.png"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "customer_form", "data-turbo-track": "reload", defer: true

  .row.navbar.navbar-dark.sticky-top.bg-dark.flex-md-nowrap.p-0.m-0.shadow
    .col
    .d-flex.col.justify-content-center
      span.d-flex.justify-content-center.col-md-3.col-lg-2.me-0.py-2.px-3 
        = button_to forms_top_path, { method: :get, form: { data: { turbo_confirm: "入力内容をリセットして初めからやり直しますか？" }}, style: "background: none;border: none;outline: none;-webkit-appearance: none;-moz-appearance: none;appearance: none;}" }
          .fs-5.text-warning.fst-italic style="text-shadow: 1px 1px orange" Sinkawasche
    .col.d-flex.justify-content-end.align-items-center style="padding-right: 0.2rem;padding-left: 1.3rem"
      = link_to forms_help_path, { class: "text_center btn btn-outline-warning shadow rounded-pill m-0 mx-md-3 px-md-4", target: :_blank }, data: { turbo: false } do
        span.text-center.small.m-0.p-0 ヘルプ

  body.bg-light
    = render partial: "components/flash_messages"
    = yield

app/views/layouts/devise_form.html.slim
doctype html
html
  head
    title
      | Sinkawasche
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = favicon_link_tag "/favicon-car.png"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "customer_form", "data-turbo-track": "reload", defer: true

    .navbar.navbar-dark.justify-content-center.sticky-top.bg-dark.flex-md-nowrap.p-0.shadow
      span.d-flex.justify-content-center.fs-5.text-warning.fst-italic.col-md-3.col-lg-2.me-0.py-2.px-3 style="text-shadow: 1px 1px orange" 
        | Sinkawasche

  body.bg-light
    = render partial: "components/flash_messages"
    = yield

app/views/layouts/email_layout.html.slim
p
  | ※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※
  br
  | こちらは送信専用のメールアドレスになります。
  br
  | 直接メールでご返信されても、確認いたしかねますのでご注意ください。
  br
  | ※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※
  br
  br
  br
  | こんにちは。
  br
  | 自動車洗車サービス『sinkawache』です。
p
  br

= yield